datasets:
  tcga_luad:
    data_dir: "${TCGA_DATA_RAW_PATH}/LUAD"
    input_pattern: "*/*DX*.svs"
    histoqc_config_path: "histolung/config/HistoQC/config_light.ini"
    magnification: 10
    label: "LUAD"
  tcga_lusc:
    data_dir: "${TCGA_DATA_RAW_PATH}/LUSC"
    input_pattern: "*/*DX*.svs"
    histoqc_config_path: "histolung/config/HistoQC/config_light.ini"
    magnification: 10
    label: "LUSC"
  cptac_lscc:
    data_dir: "${CPTAC_DATA_RAW_PATH}/CPTAC-LSCC_v10/LSCC"
    input_pattern: "*.svs"
    histoqc_config_path: "histolung/config/HistoQC/config_light.ini"
    magnification: 10
    label: "LUSC"
  cptac_luad:
    data_dir: "${CPTAC_DATA_RAW_PATH}/CPTAC-LUAD_v12/LUAD"
    input_pattern: "*.svs"
    histoqc_config_path: "histolung/config/HistoQC/config_light.ini"
    magnification: 10
    label: "LUAD"



histoqc_masks_basedir: "data/interim/masks"
tiles_basedir: "${TILES_BASEDIR}"
