datasets:
  tcga_luad:
    data_dir: "${TCGA_DATA_RAW_PATH}/LUAD"
    default_histoqc_config_path: "histolung/config/HistoQC/config_light.ini"
    histoqc_config_mapping: "data/interim/histoqc_config_mapping/tcga_luad_complete.yaml"
    magnification: 10
    label: "LUAD"
  tcga_lusc:
    data_dir: "${TCGA_DATA_RAW_PATH}/LUSC"
    default_histoqc_config_path: "histolung/config/HistoQC/config_light.ini"
    histoqc_config_mapping: "data/interim/histoqc_config_mapping/tcga_lusc_complete.yaml"
    magnification: 10
    label: "LUSC"
  cptac_lscc:
    data_dir: "${CPTAC_DATA_RAW_PATH}/CPTAC-LSCC_v10/LSCC"
    input_pattern: "*.svs"
    default_histoqc_config_path: "histolung/config/HistoQC/config_light.ini"
    magnification: 10
    label: "LUSC"
  cptac_luad:
    data_dir: "${CPTAC_DATA_RAW_PATH}/CPTAC-LUAD_v12/LUAD"
    input_pattern: "*.svs"
    histoqc_config_mapping: "data/interim/wsi_to_config_map/cptac_luad_mapping.csv"
    default_histoqc_config_path: "histolung/config/HistoQC/config_light.ini"
    magnification: 10
    label: "LUAD"

histoqc_masks_basedir: "data/interim/masks"
tiles_basedir: "${TILES_BASEDIR}"
